sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t petersmithca/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true petersmithca/docker-react npm run test -- --coverage
