sudo: required

services:
  - docker

before_install:
  - docker build -t petersmithca/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true petersmithca/docker-react npm run test -- --coverage
